---
format: html
---

## Teaching Experience {#teaching-experience}


&nbsp;

### Teaching Associate {#teaching-associate}

**Department of Econometrics and Business Statistics, Monash University**

Conducted the tutorial & group presentation sessions for:

- **ETC2430**: Actuarial Cash Flow Modelling, Semester 1 2024 [Handbook entry](https://handbook.monash.edu/2024/units/ETC2430?year=2024)
- **ETC2430**: Actuarial Cash Flow Modelling, Semester 1 2023 [Handbook entry](https://handbook.monash.edu/2023/units/ETC2430?year=2023)


&nbsp;

---

&nbsp;

### Temporary Demonstrator - ICT Centre {#temporary-demonstrator-ict}

**Information & Communication Technology Centre, University of Kelaniya**

Created videos, question papers, and marked answer scripts for an online lecture series:

- **Certificate Course in Computer Literacy**, Information Technology, Academic Year 2020/2021

Additionally, updated the National Vaccination database for COVID-19.


&nbsp;

---

&nbsp;

### Temporary Demonstrator - Statistics & Computer Science {#temporary-demonstrator-stat}

**Department of Statistics & Computer Science, University of Kelaniya**

Conducted tutorial and practical sessions for the following courses:

- **STAT 12542**: Optimization I, Academic Year 2018/2019
- **STAT 21522**: Optimization II, Academic Year 2018/2019
- **COST 21544**: Mathematical Foundation I, Academic Year 2019/2020
- **COST 31554**: Mathematics for Information Technology, Academic Year 2019/2020

Additionally, organized undergraduate students' final year research presentations and consultation sessions:

- **STAT 43878**: Research Project/Independent Study, Academic Year 2019/2020


